services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image:  pasingh211/wine-quality-regressor:e8d90aa
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64