name: "522"
channels:
  - conda-forge
dependencies:
  - python=3.11.7
  - pandas=2.1.4
  - pandera=0.21.0
  - numpy=1.26.4
  - scikit-learn=1.3.2
  - altair=5.4.1
  - jupyterlab=4.2.6
  - jupyterlab_server=2.27.3
  - jupyter_server=2.14.2
  - jupyter_core=5.7.2
  - jupyter_client=8.6.3
  - ipykernel=6.29.5
  - nb_conda_kernels=2.5.1
  - matplotlib=3.9.2
  - scipy=1.10.1
  - pip=24.3.1
  - vl-convert-python>=1.6.0
  - ucimlrepo=0.0.7
  - click=8.1.7
  - quarto=1.5.57
  - vegafusion=1.6.9
  - vegafusion-python-embed=1.6.9
  - quarto=1.5.57
  - pip:
      - altair-ally==0.1.1
      - deepchecks==0.18.1
