name: '522'
channels:
  - conda-forge
  - pytorch
  - anaconda
  - plotly
  - defaults
dependencies:
  - python=3.12.0
  - pandas=2.2.3
  - numpy=1.26.4
  - scikit-learn=1.5.2
  - altair=5.4.1
  - jupyterlab=4.2.6
  - jupyterlab_server=2.27.3
  - jupyter_server=2.14.2
  - jupyter_core=5.7.2
  - jupyter_client=8.6.3
  - ipykernel=6.29.5
  - nb_conda_kernels=2.5.1
  - matplotlib=3.9.2
  - scipy=1.14.1
  - vega_datasets
  - graphviz
  - python-graphviz
  - eli5
  - shap
  - jinja2
  - lightgbm
  - spacy
  - xgboost
  - catboost
  - nltk
  - imbalanced-learn
  - torchvision
  - torchaudio
  - pytorch
  - autograd
  - plotly
  - panel
  - watchfiles
  - wikipedia
  - requests
  - pip=24.3.1
  - vl-convert-python>=1.6.0
  - pip:
    - altair-ally>=0.1.1
    - ucimlrepo==0.0.7
    - vegafusion==1.6.9
    - vegafusion-python-embed==1.6.9
    - mglearn
    - spacymoji
    - otter-grader>=6.0
    - transformers
    - datasets
    - ultralytics
    - psutil>=5.7.2